# docker-compose build --no-cache
# docker-compose up
version: '3.4'

services:
  web:
    hostname: hostweb
    build:
      context: ./TestAppWeb
      dockerfile: Dockerfile
    ports:
      - "5000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
  
  api:
    hostname: hostapi
    build:
      context: ./TestApi
      dockerfile: Dockerfile
    ports:
      - "7500"