# docker-compose build --no-cache
# docker-compose up
version: '3.4'

services:
  api:
    hostname: hostapi
    build:
      context: ./TestApi
      dockerfile: Dockerfile
    ports:
      - "7500"
  web:
    hostname: hostweb
    build:
      context: ./TestAppWeb
      dockerfile: Dockerfile
    ports:
      - "5000"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        max_attempts: 3
  nginx:
    container_name: test-nginx
    hostname: hostnginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "4000"

# docker-compose up --scale web=3