# docker-compose build --no-cache
# docker-compose up
version: '3.4'

services:
  web:
    container_name: test-web
    build:
      context: ./TestAppWeb
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        max_attempts: 3
  
  api:
    container_name: test-web-api
    hostname: hostapi
    build:
      context: ./TestApi
      dockerfile: Dockerfile
    ports:
      - "7500:7500"